package com.example.demo.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum Json {

    DATA_INGESTION_JSON("{\n"
            + "  \"type\": \"index_parallel\",\n"
            + "  \"spec\": {\n"
            + "    \"ioConfig\": {\n"
            + "      \"type\": \"index_parallel\",\n"
            + "      \"inputSource\": {\n"
            + "        \"type\": \"local\",\n"
            + "        \"baseDir\": \"/opt/druid\",\n"
            + "        \"filter\": \"raw-data.csv\"\n"
            + "      },\n"
            + "      \"inputFormat\": {\n"
            + "        \"type\": \"csv\",\n"
            + "        \"findColumnsFromHeader\": true\n"
            + "      }\n"
            + "    },\n"
            + "    \"tuningConfig\": {\n"
            + "      \"type\": \"index_parallel\",\n"
            + "      \"partitionsSpec\": {\n"
            + "        \"type\": \"dynamic\"\n"
            + "      },\n"
            + "      \"maxNumConcurrentSubTasks\": 2\n"
            + "    },\n"
            + "    \"dataSchema\": {\n"
            + "      \"dataSource\": \"amazon-india-sales-report\",\n"
            + "      \"timestampSpec\": {\n"
            + "        \"column\": \"Date\",\n"
            + "        \"format\": \"MM-dd-yy\"\n"
            + "      },\n"
            + "      \"transformSpec\": {},\n"
            + "      \"dimensionsSpec\": {\n"
            + "        \"dimensions\": [\n"
            + "          \"Order ID\",\n"
            + "          \"Status\",\n"
            + "          \"Fulfilment\",\n"
            + "          \"Sales Channel \",\n"
            + "          \"ship-service-level\",\n"
            + "          \"Style\",\n"
            + "          \"SKU\",\n"
            + "          \"Category\",\n"
            + "          \"Size\",\n"
            + "          \"ASIN\",\n"
            + "          \"Courier Status\",\n"
            + "          \"currency\",\n"
            + "          \"ship-city\",\n"
            + "          \"ship-state\",\n"
            + "          \"ship-country\",\n"
            + "          \"promotion-ids\",\n"
            + "          \"B2B\",\n"
            + "          \"fulfilled-by\"\n"
            + "        ]\n"
            + "      },\n"
            + "      \"granularitySpec\": {\n"
            + "        \"queryGranularity\": \"day\",\n"
            + "        \"rollup\": true,\n"
            + "        \"segmentGranularity\": \"day\"\n"
            + "      },\n"
            + "      \"metricsSpec\": [\n"
            + "        {\n"
            + "          \"name\": \"count\",\n"
            + "          \"type\": \"count\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"name\": \"total_quantity_sold\",\n"
            + "          \"type\": \"longSum\",\n"
            + "          \"fieldName\": \"Qty\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"name\": \"sum_amount\",\n"
            + "          \"type\": \"doubleSum\",\n"
            + "          \"fieldName\": \"Amount\"\n"
            + "        }\n"
            + "      ]\n"
            + "    }\n"
            + "  }\n"
            + "}");

    private final String jsonString;
}
